// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7e8cS0jvDZYR-YMVr2eaP5n4R7MEFdxk',
    appId: '1:266477025524:web:d6bb2bbfef4c1b963a06a1',
    messagingSenderId: '266477025524',
    projectId: 'eduprepai-ded1a',
    authDomain: 'eduprepai-ded1a.firebaseapp.com',
    storageBucket: 'eduprepai-ded1a.firebasestorage.app',
    measurementId: 'G-71Q2XY56F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEtXvKnN0cLhSAf6TOkiKjwUUwtXu1OI',
    appId: '1:266477025524:android:4c486c8fc139ad7b3a06a1',
    messagingSenderId: '266477025524',
    projectId: 'eduprepai-ded1a',
    storageBucket: 'eduprepai-ded1a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7e8cS0jvDZYR-YMVr2eaP5n4R7MEFdxk',
    appId: '1:266477025524:web:a43a492ab32933ae3a06a1',
    messagingSenderId: '266477025524',
    projectId: 'eduprepai-ded1a',
    authDomain: 'eduprepai-ded1a.firebaseapp.com',
    storageBucket: 'eduprepai-ded1a.firebasestorage.app',
    measurementId: 'G-VBQFMY3XY2',
  );
}
